### ISSUE TITLE
Readme Clarification

### ISSUE THREAD

**Issue by martinezjf2** [learn-co-curriculum/phase-0-html-album-cover-lab#21]
### Canvas Link

https://learning.flatironschool.com/courses/6150/assignments/209287?module_item_id=482782

### Concern

The lab states: The files you need are provided in the 'images' folder, but you'll have to write the correct URL paths (like http://..../image-name) in order for them to display correctly. 
​
Need to clarify if the student will be using a value of an HTTPS link, or that path of the image within the lab directory. Students seem confused because the tests are looking for an HTTPS link, but the instructions seem to say to use the images from the images directory.

### Suggested Changes

Clarify if the student will be using an HTTPS link for the images and provide the links within the readme OR adjust the vocabulary and the example so the student can use the directory image path such so "./images/columbia-logo.png" instead of the example (like http://..../image-name)

**Comment by lizbur10** [comment]
Thanks @martinezjf2! The instructions have been updated 💙
