### ISSUE TITLE
Back Cover: H3 should be partial <strong>

### ISSUE THREAD

**Issue by anikajb92** [learn-co-curriculum/phase-0-html-album-cover-lab#3]
(back_cover.children.select {|ch| ch.name == "h3"}[0].children.first.text).to include("FROM <strong>DESPICABLE ME 2</strong>"), "An 'h3' tag should contain the text 'FROM <strong>DESPICABLE ME 2</strong>'" rather than just "FROM DESPICABLE ME"

**Comment by lizbur10** [comment]
Hi there! Thank you for spotting this issue and providing feedback. The test instructions have been updated to correct the error.

Thanks for contributing to the Flatiron School curriculum 💙
