### ISSUE TITLE
Header tags used to resize are not WCAG 2.0 compliant

### ISSUE THREAD

**Issue by sindano1** [learn-co-curriculum/phase-0-html-album-cover-lab#9]
Not an issue but something to consider: Could there be a note within this lesson that using headers to adjust the size of text creates difficult to navigate pages for screen readers? "Headings create a document outline that helps screen readers navigate a document".

https://css-tricks.com/accessible-font-sizing-explained/

**Comment by graciemcguire** [comment]
Hi @sindano1! 
Thank you for raising this issue. Web accessibility is incredibly important and unfortunately a lot of our older labs haven't been updated to this very necessary standard.
We are currently working on overhauling and auditing the entire software engineering curriculum to be accessible and this lab will definitely be flagged for those changes.
Thanks again for raising this issue, we really appreciate it!
